apiVersion: v1
kind: ConfigMap
metadata:
  name: traefiktoml
binaryData:
{{ range $path, $bytes := .Files.Glob (printf "../../../Configuration_Files/traefik/config/traefik.toml")}}
{{ $name := base $path }}
{{- printf "%s" $name}}{{ print ": "}}{{ $.Files.Get $path | b64enc }}
{{ end }}
