apiVersion: v1
kind: ConfigMap
metadata:
  name: traefikcerts
binaryData:
{{ range $path, $bytes := .Files.Glob (printf "../../../StartupScripts/traefik/certs/**")}}
{{ $name := base $path }}
{{- printf "%s" $name}}{{ print ": "}}{{ $.Files.Get $path | b64enc }}
{{ end }}
