apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-config
data:
  config.yml: |
    ---
        title: "Cyber Information Platform"


        header: true
        footer: false

        # Optional theme customization
        theme: default
        colors:
          light:
            highlight-primary: "#3367d6"
            highlight-secondary: "#4285f4"
            highlight-hover: "#5a95f5"
            background: "#f5f5f5"
            card-background: "#ffffff"
            text: "#363636"
            text-header: "#ffffff"
            text-title: "#303030"
            text-subtitle: "#424242"
            card-shadow: rgba(0, 0, 0, 0.1)
            link: "#3273dc"
            link-hover: "#363636"
          dark:
            highlight-primary: "#3367d6"
            highlight-secondary: "#4285f4"
            highlight-hover: "#5a95f5"
            background: "#131313"
            card-background: "#2b2b2b"
            text: "#eaeaea"
            text-header: "#ffffff"
            text-title: "#fafafa"
            text-subtitle: "#f5f5f5"
            card-shadow: rgba(0, 0, 0, 0.4)
            link: "#3273dc"
            link-hover: "#ffdd57"

        links: []

        # Services
        # First level array represent a group.
        # Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
        services:
          - name: "Applications"
            icon: "fas fa-cloud"
            items:
              - name: "MISP"
                subtitle: "Malware Information Sharing Platform"
                url: "https://misp.local"
              - name: "TheHive"
                subtitle: "Incident Tracking and Ticketing"
                url: "https://hive.local"
              - name: "Cortex"
                subtitle: "Data enrichment automation"
                url: "https://cortex.local"
              - name: "Gitea"
                url: "https://gitea.local"
              - name: "Wiki"
                url: "https://dokuwiki.local"
              - name: "Walkthrough"
                url: "https://walk.local"
              - name: "EtherPad"
                subtitle: "Google docs, but worse"
                url: "https://etherpad.local"
              - name: "EtherCalc"
                subtitle: "Google sheets, but worse"
                url: "https://ethercalc.local"
              - name: "DevDocs"
                url: "https://devdocs.local"
              - name: "Draw.io"
                url: "https://drawio.local"
              - name: "CyberChef"
                url: "https://cyberchef.local"
              - name: "Regexr"
                subtitle: "Let's be real, no one will use this"
                url: "https://regexr.local"
              - name: "Crontab Guru"
                url: "https://cron.local"
              - name: "RocketChat"
                url: "https://rocketchat.local"
              - name: "Vault"
                subtitle: "Secure password managment"
                url: "https://vaultwarden.local"
              - name: "PwnDrop"
                subtitle: "Secure File Transfers"
                url: "https://pwndrop.local"
          - name: "Orchestration Services"
            icon: "fas fa-cloud"
            items:
              - name: "Grafana"
                url: "https://grafana.local"
              - name: "Prometheus"
                url: "https://Prometheus.local"
              - name: "Alert Manager"
                url: "https://alertmanager.local"
              - name: "Unsee"
                url: "https://unsee.local"
              - name: "Traefik"
                url: "https://Traefik.local"
                subtitle: "Docker Network Proxy"
              - name: "PiHole"
                url: "https://pihole.local/admin"
                subtitle: "Dockerized DNS"

