apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-db
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
