apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etherpad-db
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.db.size }}
