apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etherpad-data
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.data.size }}
