apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misp-www
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.www.size }}
