apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
          server {  
            listen 80;
            server_name  _;

            root /var/www/html/crontab.guru;
            index index.html;

            location / {
            try_files $uri $uri/ =404;
            }
          }
