apiVersion: v1
kind: Service
metadata:
  name: {{ include "cron.fullname" . }}
  labels:
    {{- include "cron.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "cron.selectorLabels" . | nindent 4 }}
