apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thp-cortex
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.cortex.size }}

