apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thp-es
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.es.size }}

