apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thp-hive-db
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.hivedb.size }}

