apiVersion: v1
kind: ConfigMap
metadata:
  name: thp-hive-conf
data:
  application.conf: |
          play.http.secret.key="imjusttestingthings"
          play.ws.ssl.loose.acceptAnyCertificate = true
          ## For test only !
          db.janusgraph {
            storage.backend: berkeleyje
            storage.directory: /opt/thp/thehive/db
            berkeleyje.freeDisk: 200

            ## Index configuration
            index {
              search {
                backend: lucene
                directory: /opt/thp/thehive/index
             }
            } 
          }

          storage {
            provider: localfs
            localfs.location: /opt/thp/thehive/data
          }

          play.http.parser.maxDiskBuffer: 50MB

          play.modules.enabled += org.thp.thehive.connector.cortex.CortexModule
          cortex {
            servers = [
              {
                name = local
                url = "http://0.0.0.0:9001"
                auth {
                  type = "bearer"
                  key = "API_KEY_HERE"
                }
              }
            ]
            # Check job update time intervalcortex
            refreshDelay = 5 seconds
            # Maximum number of successive errors before give up
            maxRetryOnError = 3
            # Check remote Cortex status time interval
            statusCheckInterval = 30 seconds
          }

          play.modules.enabled += org.thp.thehive.connector.misp.MispModule
          misp {
            interval: 1 hour
            servers: [
              {
                name = "Misp"            # MISP name
                url = "https://misp/" # URL or MISP
                auth {
                  type = key
                  key = "KEYHERE"             # MISP API key
                }
                wsConfig { ssl { loose { acceptAnyCertificate: true } } }
              }
            ]
          }

